### ISSUE TITLE
System.ArgumentNullException in ConsoleApp

### ISSUE THREAD

**Issue by haruair** [aliencube/Scissorhands.NET#24]
I got the trace from the ConsoleApp when I run the app using `dnx run`. Is there any requirements for CLI? (FYI, I installed dependencies via `dnu restore`.)

```
System.ArgumentNullException: Value cannot be null.
Parameter name: instance
   at Autofac.RegistrationExtensions.RegisterInstance[T](ContainerBuilder builder, T instance)
   at Aliencube.Scissorhands.WebApp.Configs.DependencyConfig.RegisterAppSettings(ContainerBuilder builder, IConfiguration configuration)
   at Aliencube.Scissorhands.WebApp.Configs.DependencyConfig.Register(IServiceCollection services, IConfiguration configuration)
   at Aliencube.Scissorhands.WebApp.Startup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureApplicationServices()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.Start()
   at Microsoft.AspNet.TestHost.TestServer..ctor(WebHostBuilder builder)
   at Microsoft.AspNet.TestHost.TestServer.Create(Action`1 configureApp, Func`2 configureServices)
   at Aliencube.Scissorhands.ConsoleApp.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

My env is below:
```
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16231
 Type:         CoreClr
 Architecture: x64
 OS Name:      Darwin
 OS Version:   10.10
 Runtime Id:   osx.10.10-x64
```

**Comment by haruair** [comment]
False alarm! I should check the slack.
